[tool.poetry]
name = "langchainmyreact"
version = "0.0.1"
description = "LangChain ReAct implementation"
authors = ["masashimorita"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"